// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7k_M6GMX19mACkYxqCclgoLEAmj4UkJ8',
    appId: '1:493130797764:web:4709ede45390ab72fd6f91',
    messagingSenderId: '493130797764',
    projectId: 'fix-my-ride-a709c',
    authDomain: 'fix-my-ride-a709c.firebaseapp.com',
    storageBucket: 'fix-my-ride-a709c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAm6NLu5sl3YAiCWdJmYSuNEvrDt8RMoA',
    appId: '1:493130797764:android:b0a934525349de63fd6f91',
    messagingSenderId: '493130797764',
    projectId: 'fix-my-ride-a709c',
    storageBucket: 'fix-my-ride-a709c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHUdwfl32u1ls4S52zAXjX3AVdQt6NPGg',
    appId: '1:493130797764:ios:68ba990e36313e0ffd6f91',
    messagingSenderId: '493130797764',
    projectId: 'fix-my-ride-a709c',
    storageBucket: 'fix-my-ride-a709c.firebasestorage.app',
    iosBundleId: 'com.example.adminFixMyRide',
  );
}
