// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGkx1j27V9K_xjvkwB9ERRimdMqHGvCeg',
    appId: '1:479359656011:web:a379b84e15c42f0694edce',
    messagingSenderId: '479359656011',
    projectId: 'urban-landscape-fef82',
    authDomain: 'urban-landscape-fef82.firebaseapp.com',
    storageBucket: 'urban-landscape-fef82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6DU_VI1Quk6wFX6vEC6CG30ogm-0_Otg',
    appId: '1:479359656011:android:304156188f1a963094edce',
    messagingSenderId: '479359656011',
    projectId: 'urban-landscape-fef82',
    storageBucket: 'urban-landscape-fef82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy1Yc8BO5b2W9uniJIJ6pkDP9Nj3iUBDg',
    appId: '1:479359656011:ios:68592042ce36882694edce',
    messagingSenderId: '479359656011',
    projectId: 'urban-landscape-fef82',
    storageBucket: 'urban-landscape-fef82.firebasestorage.app',
    iosBundleId: 'com.example.adminFixMyRide',
  );
}
